name: Build Docker image

on:
  workflow_dispatch:
  push:
      tags:
      - v*

jobs:
  Build-image:
    runs-on: ubuntu-20.04
    steps:

      - name: 检查
        uses: actions/checkout@v3

      - name: 初始化QEMU
        uses: docker/setup-qemu-action@v2

      - name: 初始化Buildx
        uses: docker/setup-buildx-action@v2

      - name: 登录Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: 构建webui镜像
        id: docker_build_webui
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./webui/Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64
          tags: jyishit/zhenxun_webui:latest

      - name: 构建gocq镜像
        id: docker_build_gocq
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./gocq/Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64
          tags: jyishit/go-cqhttp:latest

      - name: 构建bot镜像
        id: docker_build_bot
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./zhenxun/Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64
          tags: jyishit/zhenxun_bot:latest
